# 是否开启认证
auth_enabled: false

server:
  http_listen_port: 3100
  log_level: info

# 写入 ingester 配置
ingester:
  lifecycler:
    ring:
      kvstore:
        store: inmemory
      replication_factor: 1
  chunk_idle_period: 5m
  chunk_retain_period: 30s

# schema 配置
schema_config:
  configs:
    - from: 2020-10-24
      store: boltdb-shipper
      object_store: filesystem
      schema: v11
      index:
        prefix: index_
        period: 24h

# 存储配置
storage_config:
  boltdb_shipper:
    active_index_directory: /loki/index
    cache_location: /loki/cache
  filesystem:
    directory: /loki/chunks

# compactor 配置
compactor:
  working_directory: /loki/compactor

# 限流与过期日志策略
limits_config:
  reject_old_samples: true
  reject_old_samples_max_age: 168h
  per_stream_rate_limit: 10MB
  per_stream_rate_limit_burst: 20MB
  max_entries_limit_per_query: 50000
  allow_structured_metadata: false   # ⚠️ 新增，关闭结构化元数据

